#!/usr/bin/env bash

# Documentation: https://docs.fedoraproject.org/en-US/fedora-accounts/user/
# This package needs the fedora-packager-kerberos to run the fkinit and the 1Password cli tool.

echo "Requesting Fedora kerberos ticket"
fkinit -u $(op read 'op://Personal/Fedora/username') <<< "$(op read 'op://Personal/Fedora/password')$(op read 'op://Personal/Fedora/one-time password?attribute=otp')"

