#!/usr/bin/env bash

# Prints Lorem ipsum to the stdout. I use this script more than I will admit.
# By default it prints one paragraph. Pass a number and it will print that
# paragraph N times.

# From the Wikipedia page
# https://en.wikipedia.org/wiki/Lorem_ipsum#Example_text
text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

N=1
# I don't have a better way to check if something is a number...
if [[ $1 =~ ^[0-9]+$ ]]; then
	N=$1
fi

for ((i = 1 ; i <= N ; i++)); do
	printf "%s \n\n" "$text"
done

