local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>m', builtin.marks, {})
vim.keymap.set('n', '<leader>b', builtin.buffers, {})
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.git_files, {})
vim.keymap.set('n', '<leader>fs', builtin.lsp_document_symbols, {})
vim.keymap.set('n', '<leader>fws', function()
	builtin.lsp_workspace_symbols({ query = vim.fn.input("symbol > ") })
end)
vim.keymap.set('n', '<leader>ft', function()
	builtin.grep_string({ search = vim.fn.input("grep > ") })
end)
