# Set display notifications time to 3 seconds
set -g display-time 3000

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Start counting sessions and windows from 1. Based on one of the best answers
# ever: https://unix.stackexchange.com/a/755474
bind-key s choose-tree -ZsK '#{?#{e|<:#{line},9},#{e|+:1,#{line}},#{?#{e|<:#{line},35},M-#{a:#{e|+:97,#{e|-:#{line},9}}},}}'
bind-key w choose-tree -ZwK '#{?#{e|<:#{line},9},#{e|+:1,#{line}},#{?#{e|<:#{line},35},M-#{a:#{e|+:97,#{e|-:#{line},9}}},}}'

# Renumber windows when one is closed.
set -g renumber-windows on

# Increase scrollback history.
set -g history-limit 10000

# Set history file
set -g history-file ~/.tmux_history

# Alt + s will save the whole history to a file in /tmp
bind-key -n M-s run-shell 'file="/tmp/tmux-history-$(date +%Y%m%d-%H%M%S).log"; tmux capture-pane -p -S - > "$file"; tmux display-message "History saved to $file"'

# Use vi-style keys in copy mode.
setw -g mode-keys vi

# Reduce the escape-key delay.
set -sg escape-time 0

# Reload the configuration with Prefix + r.
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Split panes while keeping the current directory.
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# New windows start in the current directory.
bind c new-window -c "#{pane_current_path}"

# Check scripts/dot-local/scripts/tmux-sessions
set -g status-left-length 50
set -g status-right-length 150
bind-key -r f run-shell "tmux neww tmux-sessions"

